# Generated by Django 4.2 on 2023-05-13 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0004_alter_book_options_remove_book_genre_and_more'),
        ('bookshelf', '0004_order_admin_alter_book_id_alter_user_id_wishlist_and_more'),
    ]

    operations = [
    ]
