# Generated by Django 4.2 on 2023-06-04 06:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bookshelf', '0008_remove_wishlist_book_id_remove_wishlist_user_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='full_name',
        ),
    ]
